// GENERATED by buildtools/gen_web_assets.py — do not edit by hand.
// Edit data/palette.json and re-run that script.

window.PALETTE_DATA = {
  "format_version": 1,
  "_comment": "The single source of truth for everything placeable in a level. Godot reads this file directly (scripts/level/PaletteRegistry.gd). The web editor reads a generated copy (web_editor/js/palette.data.js) produced by buildtools/gen_web_assets.py. Add a placeable HERE and both sides get it. Re-run that script after editing. 'decor' items are background props: free-positioned in pixels rather than snapped to the tile grid, and never collidable.",
  "tiles": [
    {
      "id": 1,
      "key": "ground",
      "label": "Counter",
      "hint": "Solid floor and walls. The main thing you build with.",
      "atlas_column": 0,
      "solid": true
    },
    {
      "id": 2,
      "key": "shelf",
      "label": "Shelf",
      "hint": "You can jump up through it and land on top.",
      "atlas_column": 1,
      "solid": true,
      "one_way": true
    },
    {
      "id": 3,
      "key": "backdrop",
      "label": "Back Wall",
      "hint": "Just for looks. You walk straight through it.",
      "atlas_column": 2,
      "solid": false
    },
    {
      "id": 4,
      "key": "stone",
      "label": "Stone",
      "hint": "Solid like the counter, but grey.",
      "atlas_column": 3,
      "solid": true
    },
    {
      "id": 5,
      "key": "rope_ladder",
      "label": "Rope Ladder",
      "hint": "Climbable. Paint a column of it and hold Up or Down to go up and down.",
      "atlas_column": 4,
      "solid": false,
      "climbable": true
    }
  ],
  "entities": [
    {
      "id": "player_spawn",
      "label": "Start",
      "hint": "Where you begin. Every level needs exactly one.",
      "scene": "",
      "icon": "player_water",
      "unique": true,
      "category": "essentials",
      "params": {}
    },
    {
      "id": "level_exit",
      "label": "Exit",
      "hint": "Touch it to finish the level.",
      "scene": "res://scenes/entities/LevelExit.tscn",
      "icon": "tunnel",
      "category": "essentials",
      "params": {
        "require_boss": {
          "type": "bool",
          "default": true,
          "label": "Needs the boss beaten first"
        },
        "boss_id": {
          "type": "string",
          "default": "gummy_amalgam",
          "label": "Which boss"
        }
      }
    },
    {
      "id": "checkpoint",
      "label": "Checkpoint",
      "hint": "If you get hurt badly you come back here.",
      "scene": "res://scenes/entities/Checkpoint.tscn",
      "icon": "shrine",
      "category": "essentials",
      "params": {
        "entity_id": {
          "type": "string",
          "default": "cp",
          "label": "Name"
        }
      }
    },
    {
      "id": "fruit_gummy",
      "label": "Fruit Gummy",
      "hint": "Hops back and forth. Three icicle hits.",
      "scene": "res://scenes/entities/FruitGummy.tscn",
      "icon": "enemy_fruit_gummy",
      "category": "danger",
      "params": {
        "max_health": {
          "type": "int",
          "default": 3,
          "min": 1,
          "max": 20,
          "label": "Toughness"
        },
        "patrol_speed": {
          "type": "float",
          "default": 46.0,
          "min": 0.0,
          "max": 200.0,
          "label": "Speed"
        },
        "contact_damage": {
          "type": "int",
          "default": 1,
          "min": 0,
          "max": 5,
          "label": "Hurt on touch"
        },
        "sets_flag_on_defeat": {
          "type": "flag",
          "default": "",
          "label": "Triggers on defeat"
        },
        "requires_flag": {
          "type": "flag",
          "default": "",
          "label": "Only appears after"
        }
      }
    },
    {
      "id": "hazard_spill",
      "label": "Spill",
      "hint": "Hurts while you stand in it. Drag to make it wider.",
      "scene": "res://scenes/entities/Hazard.tscn",
      "icon": "hazard_spill",
      "category": "danger",
      "params": {
        "width_tiles": {
          "type": "int",
          "default": 1,
          "min": 1,
          "max": 20,
          "label": "How wide"
        },
        "requires_flag": {
          "type": "flag",
          "default": "",
          "label": "Only appears after"
        }
      }
    },
    {
      "id": "boss_arena",
      "label": "Boss Arena",
      "hint": "Walking in seals the room and wakes the boss.",
      "scene": "res://scenes/entities/BossArena.tscn",
      "icon": "boss_gummy_amalgam",
      "category": "danger",
      "params": {
        "entity_id": {
          "type": "string",
          "default": "arena",
          "label": "Name"
        },
        "boss_scene_path": {
          "type": "string",
          "default": "res://scenes/entities/BossGummyAmalgam.tscn",
          "label": "Which boss"
        },
        "width_tiles": {
          "type": "int",
          "default": 22,
          "min": 8,
          "max": 60,
          "label": "Room width"
        },
        "height_tiles": {
          "type": "int",
          "default": 10,
          "min": 5,
          "max": 30,
          "label": "Room height"
        },
        "trigger_width_tiles": {
          "type": "int",
          "default": 8,
          "min": 1,
          "max": 40,
          "label": "How far in before the doors shut"
        },
        "requires_flag": {
          "type": "flag",
          "default": "",
          "label": "Only appears after"
        }
      }
    },
    {
      "id": "rope_anchor",
      "label": "Rope Anchor",
      "hint": "Lash to it. Give it a length and a rope hangs down to climb.",
      "scene": "res://scenes/entities/RopeAnchor.tscn",
      "icon": "rope_anchor",
      "category": "traversal",
      "params": {
        "rope_length": {
          "type": "int",
          "default": 0,
          "min": 0,
          "max": 24,
          "label": "Rope length (0 = lash only)"
        }
      }
    },
    {
      "id": "shrine",
      "label": "Shape Shrine",
      "hint": "Teaches a shape. Put one before you need the shape.",
      "scene": "res://scenes/entities/Shrine.tscn",
      "icon": "shrine",
      "category": "traversal",
      "params": {
        "shape_id": {
          "type": "enum",
          "default": "icicle",
          "options": [
            "icicle",
            "rope",
            "drill"
          ],
          "label": "Which shape"
        }
      }
    },
    {
      "id": "breakable_wall",
      "label": "Cracked Stone",
      "hint": "Only the drill opens it. Hide something good behind it.",
      "scene": "res://scenes/entities/BreakableWall.tscn",
      "icon": "stone_block",
      "category": "traversal",
      "params": {
        "entity_id": {
          "type": "string",
          "default": "wall",
          "label": "Name"
        },
        "required_shape": {
          "type": "enum",
          "default": "drill",
          "options": [
            "icicle",
            "rope",
            "drill"
          ],
          "label": "Opened by"
        },
        "tiles_wide": {
          "type": "int",
          "default": 1,
          "min": 1,
          "max": 10,
          "label": "Width"
        },
        "tiles_tall": {
          "type": "int",
          "default": 3,
          "min": 1,
          "max": 20,
          "label": "Height"
        }
      }
    },
    {
      "id": "tunnel",
      "label": "Secret Tunnel",
      "hint": "After you beat the level these join up for fast travel.",
      "scene": "res://scenes/entities/TunnelEndpoint.tscn",
      "icon": "tunnel",
      "category": "traversal",
      "params": {
        "endpoint_id": {
          "type": "string",
          "default": "start",
          "label": "Name"
        },
        "endpoint_label": {
          "type": "string",
          "default": "The Counter",
          "label": "Sign text"
        }
      }
    },
    {
      "id": "chest",
      "label": "Chest",
      "hint": "Holds a cup or a recipe. Hide it off the main path.",
      "scene": "res://scenes/entities/Chest.tscn",
      "icon": "chest",
      "category": "treasure",
      "params": {
        "entity_id": {
          "type": "string",
          "default": "chest",
          "label": "Name"
        },
        "contents_kind": {
          "type": "enum",
          "default": "cup",
          "options": [
            "cup",
            "recipe"
          ],
          "label": "Holds a"
        },
        "contents_id": {
          "type": "string",
          "default": "glass",
          "label": "Which one"
        },
        "sets_flag_on_open": {
          "type": "flag",
          "default": "",
          "label": "Triggers after open"
        },
        "requires_flag": {
          "type": "flag",
          "default": "",
          "label": "Only appears after"
        }
      }
    },
    {
      "id": "npc",
      "label": "Person",
      "hint": "Someone to talk to. Pick who they are, then write what they say.",
      "scene": "res://scenes/entities/Npc.tscn",
      "icon": "chef",
      "_comment_icon": "The editor draws whichever person this is, not always the chef. icon_by_value maps the npc_type param to art; Npc.TYPES in scripts/entities/Npc.gd names the same files and TestRunner checks the two agree.",
      "icon_param": "npc_type",
      "icon_by_value": {
        "chef": "chef",
        "blob": "npc_blob",
        "mouse": "npc_mouse",
        "fly": "npc_fly"
      },
      "category": "treasure",
      "params": {
        "npc_type": {
          "type": "enum",
          "default": "chef",
          "options": [
            "chef",
            "blob",
            "mouse",
            "fly"
          ],
          "label": "Who is it"
        },
        "dialogue": {
          "type": "dialogue",
          "default": [],
          "label": "What they say"
        },
        "gives_cookbook": {
          "type": "bool",
          "default": false,
          "label": "Hands over the cookbook (chef only)"
        },
        "requires_flag": {
          "type": "flag",
          "default": "",
          "label": "Only appears after"
        },
        "sets_flag_on_talk": {
          "type": "flag",
          "default": "",
          "label": "Triggers after talking"
        }
      }
    },
    {
      "id": "sign",
      "label": "Completion Sign",
      "hint": "Shows how much of the cookbook is filled in.",
      "scene": "res://scenes/entities/CompletionSign.tscn",
      "icon": "sign",
      "category": "treasure",
      "params": {
        "requires_flag": {
          "type": "flag",
          "default": "",
          "label": "Only appears after"
        }
      }
    }
  ],
  "categories": [
    {
      "id": "essentials",
      "label": "Essentials"
    },
    {
      "id": "danger",
      "label": "Danger"
    },
    {
      "id": "traversal",
      "label": "Getting Around"
    },
    {
      "id": "treasure",
      "label": "Treasure"
    }
  ],
  "decor": [
    {
      "id": "window",
      "label": "Window",
      "hint": "Daylight behind everything.",
      "sprite": "decor_window"
    },
    {
      "id": "cupboard",
      "label": "Cupboard",
      "hint": "A big shape to break up a long wall.",
      "sprite": "decor_cupboard"
    },
    {
      "id": "shelf",
      "label": "Wall Shelf",
      "hint": "Decoration only \u2014 you can't stand on it.",
      "sprite": "decor_shelf"
    },
    {
      "id": "jar",
      "label": "Jar",
      "hint": "Small clutter. Good in groups.",
      "sprite": "decor_jar"
    },
    {
      "id": "plant",
      "label": "Plant",
      "hint": "Something green.",
      "sprite": "decor_plant"
    },
    {
      "id": "clock",
      "label": "Clock",
      "hint": "It's always breakfast time somewhere.",
      "sprite": "decor_clock"
    }
  ],
  "decor_params": {
    "scale": {
      "type": "float",
      "default": 1.0,
      "min": 0.2,
      "max": 4.0,
      "label": "Size"
    },
    "parallax": {
      "type": "float",
      "default": 0.9,
      "min": 0.3,
      "max": 1.0,
      "label": "How far away (1 = right behind you)"
    },
    "flip": {
      "type": "bool",
      "default": false,
      "label": "Face the other way"
    },
    "tint": {
      "type": "color",
      "default": "#ffffff",
      "label": "Colour"
    }
  },
  "dialogue_line_params": {
    "text": {
      "type": "text",
      "default": "",
      "label": "What they say"
    },
    "when": {
      "type": "flag",
      "default": "",
      "label": "Only if this happened"
    },
    "unless": {
      "type": "flag",
      "default": "",
      "label": "Unless this happened"
    },
    "set": {
      "type": "flag",
      "default": "",
      "label": "Then remember"
    },
    "give_kind": {
      "type": "enum",
      "default": "none",
      "options": [
        "none",
        "recipe",
        "cup",
        "shape",
        "liquid"
      ],
      "label": "Give the player"
    },
    "give_id": {
      "type": "string",
      "default": "",
      "label": "Which one"
    }
  }
};
